#!/bin/bash
# ln -sn
#cp .zshrc ~/.zshrc
#cp .p10k.zsh ~/.p10k.zsh
wget -O - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k


ln -snf $(pwd)/.zshrc ~/.zshrc
ln -snf $(pwd)/.p10k.zsh ~/.p10k.zsh
